"""empty message

Revision ID: c35833aaebb2
Revises: ab8bb37691db
Create Date: 2019-05-18 21:51:34.900982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c35833aaebb2'
down_revision = 'ab8bb37691db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('app_secret', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'user', ['app_secret'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'app_secret')
    # ### end Alembic commands ###
